<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * Product media data template
 *
 * @var $block \Magento\Catalog\Block\Product\View\Gallery
 */
// $preorderAvailable = $_product->getResource()->getAttribute('pre_order');
// $preorderAvailable = $preorderAvailable->getFrontend()->getValue($_product);
// $class = "pre-order";
// if($preorderAvailable == "Yes") {
//     $pPreOrder ="<p class= $class > Pre Order </p>";
// }

?>
<?php $_product = $block->getProduct(); ?>
<?php
$images = $block->getGalleryImages()->getItems();
$mainImage = current(array_filter($images, function ($img) use ($block) {
    return $block->isMainImage($img);
}));

if (!empty($images) && empty($mainImage)) {
    $mainImage = $block->getGalleryImages()->getFirstItem();
}

$helper = $block->getData('imageHelper');
$mainImageData = $mainImage ?
    $mainImage->getData('medium_image_url') :
    $helper->getDefaultPlaceholderUrl('image');
?>
<?php
    $preorderAvailable = $_product->getResource()->getAttribute('pre_oder_or_sale');
$preorderAvailable = $preorderAvailable->getFrontend()->getValue($_product);
if(empty($preorderAvailable)){}
else{
    if($preorderAvailable==="Sale"){
        $class = "sale-label";
        echo "<p class= '$class' > Sale </p>";
    }elseif($preorderAvailable==="Pre Order"){
        $class = "pre-order-label";
        echo "<p class= '$class' > Pre Order </p>";
    }
}
    ?>
<div class="gallery-placeholder _block-content-loading" data-gallery-role="gallery-placeholder">
    <img
        alt="main product photo"
        class="gallery-placeholder__image"
        src="<?= /* @noEscape */ $mainImageData ?>"
    /> 
</div>

<script type="text/x-magento-init">
    {
        "[data-gallery-role=gallery-placeholder]": {
            "mage/gallery/gallery": {
                "mixins":["magnifier/magnify"],
                "magnifierOpts": <?= /* @noEscape */ $block->getMagnifier() ?>,
                "data": <?= /* @noEscape */ $block->getGalleryImagesJson() ?>,
                "options": <?= /* @noEscape */ $block->getGalleryOptions()->getOptionsJson() ?>,
                "fullscreen": <?= /* @noEscape */ $block->getGalleryOptions()->getFSOptionsJson() ?>,
                 "breakpoints": <?= /* @noEscape */ $block->getBreakpoints() ?>
            }
        }
    }
</script>
