<div class="header-top-left">
<?php
echo $block->getLayout()
    ->createBlock('Magento\Cms\Block\Block')
    ->setBlockId('header-top-left')
    ->toHtml();
?>
</div>
<div class="header-top-middle">
<?php
echo $block->getLayout()
->createBlock('Magento\Cms\Block\Block')
->setBlockId('header-top-middle')
->toHtml();
?>
</div>
<div class="header-top-right">
<?php
echo $block->getLayout()
->createBlock('Magento\Cms\Block\Block')
->setBlockId('header-top-right')
->toHtml();
?>
</div>
<div class="header-top-left-mobile">
<?php
echo $block->getLayout()
->createBlock('Magento\Cms\Block\Block')
->setBlockId('header-top-left-mobile')
->toHtml();
?>
</div>
<div class="header-top-right-mobile">
<?php
echo $block->getLayout()
->createBlock('Magento\Cms\Block\Block')
->setBlockId('header-top-right-mobile')
->toHtml();
?>
</div>
